### ISSUE TITLE
Mouse scrolling support

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/embedder#18]
Currently scrolling with mouse scroll wheel has no effect on physical and emulator devices (including mobile/TV/common).

**Comment by JSUYA** [comment]
When I tested on the TV device, the wheel scroll of the mouse worked.
(I tested it by adding SingleChildScrollView() to the default flutter-tizen app.)
As far as I know, the emulator's mouse wheel doesn't support.

**Comment by swift-kim** [comment]
Thanks. I confirmed that the scrolling works on physical TV and common devices (although it's [not very smooth](https://github.com/flutter/flutter/issues/32120) and the scroll speed is a bit too slow). The issue is only for emulators and I think it will never get fixed.
