### ISSUE TITLE
Need an API which can get the window geometry.

### ISSUE THREAD

**Issue by hyue7** [flutter-tizen/embedder#2]
https://github.com/flutter-tizen/plugins/pull/468#discussion_r1006328928
In this pull request comments, parameters `w` and `h` of `player_set_ecore_wl_display` expect window's geometry. But, I can't find any public API to get geometry of window.
In order to get geometry of window, maybe need an api which can get the width and height of window.
Please help check if there is any api can implement it or need to add an new api to Embedder.

**Comment by JSUYA** [comment]
In the case of the attached comment, the type of native handle looks like `Ecore_Wl2_Window*`.
The size of the `Ecore_Wl2_Window` can be obtained using the function below.
```
#include <Ecore_Wl2.h>
void ecore_wl2_window_geometry_get(Ecore_Wl2_Window *window, int *x, int *y, int *w, int *h);
```

**Comment by hyue7** [comment]
> In the case of the attached comment, the type of native handle looks like `Ecore_Wl2_Window*`. The size of the `Ecore_Wl2_Window` can be obtained using the function below.
> 
> ```
> #include <Ecore_Wl2.h>
> void ecore_wl2_window_geometry_get(Ecore_Wl2_Window *window, int *x, int *y, int *w, int *h);
> ```

I can't find `<Ecore_Wl2.h>` this head file when build tpk. And this function `ecore_wl2_window_geometry_get` started being supported as a public API starting with 6.0.
And then, I build tpk with 6.0 api-version, it had some error that can't find `<wayland-client.h>` in `Ecore_Wl2.h`.

`/include/ecore-wl2-1/Ecore_Wl2.h:6:11: fatal error: 'wayland-client.h' file not found
# include <wayland-client.h>`

**Comment by JSUYA** [comment]
As you said, we probably need an API that returns the `Geometry` of a `FlutterDesktopViewRef`.
However, this API may take a little longer because `TizenView` as well as `TizenWindow` must be considered.

+)
In this https://github.com/flutter-tizen/plugins/pull/468#discussion_r1006328928 PR, is there any way to pass the size of  HoleBox or VideoPlayer (dart) to VideoPlayerTizenPlugin and use it?

**Comment by swift-kim** [comment]
As far as I know you can asynchronously get the window size through the [platform channel](https://github.com/flutter-tizen/embedder/blob/master/flutter/shell/platform/tizen/channels/window_channel.cc) (`getWindowGeometry`) if it fits your need.

**Comment by JSUYA** [comment]
> As far as I know you can asynchronously get the window size through the [platform channel](https://github.com/flutter-tizen/embedder/blob/master/flutter/shell/platform/tizen/channels/window_channel.cc) (`getWindowGeometry`) if it fits your need.

This problem looks to have been solved as your comment.
https://github.com/flutter-tizen/plugins/pull/468/files#diff-e46ec295edc88092e3563e1b9062cfb31ad44474e00a059ffc2f45c612c5567eR318-R329
